/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutHeaderImport } from './routes/_layout/_header'
import { Route as LayoutHeaderIndexImport } from './routes/_layout/_header/index'
import { Route as LayoutHeaderListIndexImport } from './routes/_layout/_header/list/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutHeaderRoute = LayoutHeaderImport.update({
  id: '/_header',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHeaderIndexRoute = LayoutHeaderIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutHeaderRoute,
} as any)

const LayoutHeaderListIndexRoute = LayoutHeaderListIndexImport.update({
  path: '/list/',
  getParentRoute: () => LayoutHeaderRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_header': {
      id: '/_layout/_header'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutHeaderImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_header/': {
      id: '/_layout/_header/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutHeaderIndexImport
      parentRoute: typeof LayoutHeaderImport
    }
    '/_layout/_header/list/': {
      id: '/_layout/_header/list/'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof LayoutHeaderListIndexImport
      parentRoute: typeof LayoutHeaderImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutHeaderRoute: LayoutHeaderRoute.addChildren({
      LayoutHeaderIndexRoute,
      LayoutHeaderListIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_header"
      ]
    },
    "/_layout/_header": {
      "filePath": "_layout/_header.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_header/",
        "/_layout/_header/list/"
      ]
    },
    "/_layout/_header/": {
      "filePath": "_layout/_header/index.tsx",
      "parent": "/_layout/_header"
    },
    "/_layout/_header/list/": {
      "filePath": "_layout/_header/list/index.tsx",
      "parent": "/_layout/_header"
    }
  }
}
ROUTE_MANIFEST_END */
