/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutHeaderImport } from './routes/_layout/_header'
import { Route as LayoutHeaderHeavyImport } from './routes/_layout/_header/heavy'
import { Route as LayoutHeaderPokemonsIndexImport } from './routes/_layout/_header/pokemons/index'
import { Route as LayoutHeaderPokemonsSearchImport } from './routes/_layout/_header/pokemons/search'

// Create Virtual Routes

const LayoutHeaderIndexLazyImport = createFileRoute('/_layout/_header/')()
const LayoutHeaderLightLazyImport = createFileRoute('/_layout/_header/light')()
const LayoutHeaderErrorLazyImport = createFileRoute('/_layout/_header/error')()
const LayoutHeaderPokemonsIdLazyImport = createFileRoute(
  '/_layout/_header/pokemons/$id',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutHeaderRoute = LayoutHeaderImport.update({
  id: '/_header',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutHeaderIndexLazyRoute = LayoutHeaderIndexLazyImport.update({
  path: '/',
  getParentRoute: () => LayoutHeaderRoute,
} as any).lazy(() =>
  import('./routes/_layout/_header/index.lazy').then((d) => d.Route),
)

const LayoutHeaderLightLazyRoute = LayoutHeaderLightLazyImport.update({
  path: '/light',
  getParentRoute: () => LayoutHeaderRoute,
} as any).lazy(() =>
  import('./routes/_layout/_header/light.lazy').then((d) => d.Route),
)

const LayoutHeaderErrorLazyRoute = LayoutHeaderErrorLazyImport.update({
  path: '/error',
  getParentRoute: () => LayoutHeaderRoute,
} as any).lazy(() =>
  import('./routes/_layout/_header/error.lazy').then((d) => d.Route),
)

const LayoutHeaderHeavyRoute = LayoutHeaderHeavyImport.update({
  path: '/heavy',
  getParentRoute: () => LayoutHeaderRoute,
} as any)

const LayoutHeaderPokemonsIndexRoute = LayoutHeaderPokemonsIndexImport.update({
  path: '/pokemons/',
  getParentRoute: () => LayoutHeaderRoute,
} as any)

const LayoutHeaderPokemonsIdLazyRoute = LayoutHeaderPokemonsIdLazyImport.update(
  {
    path: '/pokemons/$id',
    getParentRoute: () => LayoutHeaderRoute,
  } as any,
).lazy(() =>
  import('./routes/_layout/_header/pokemons/$id.lazy').then((d) => d.Route),
)

const LayoutHeaderPokemonsSearchRoute = LayoutHeaderPokemonsSearchImport.update(
  {
    path: '/pokemons/search',
    getParentRoute: () => LayoutHeaderRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_header': {
      id: '/_layout/_header'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutHeaderImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_header/heavy': {
      id: '/_layout/_header/heavy'
      path: '/heavy'
      fullPath: '/heavy'
      preLoaderRoute: typeof LayoutHeaderHeavyImport
      parentRoute: typeof LayoutHeaderImport
    }
    '/_layout/_header/error': {
      id: '/_layout/_header/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof LayoutHeaderErrorLazyImport
      parentRoute: typeof LayoutHeaderImport
    }
    '/_layout/_header/light': {
      id: '/_layout/_header/light'
      path: '/light'
      fullPath: '/light'
      preLoaderRoute: typeof LayoutHeaderLightLazyImport
      parentRoute: typeof LayoutHeaderImport
    }
    '/_layout/_header/': {
      id: '/_layout/_header/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutHeaderIndexLazyImport
      parentRoute: typeof LayoutHeaderImport
    }
    '/_layout/_header/pokemons/search': {
      id: '/_layout/_header/pokemons/search'
      path: '/pokemons/search'
      fullPath: '/pokemons/search'
      preLoaderRoute: typeof LayoutHeaderPokemonsSearchImport
      parentRoute: typeof LayoutHeaderImport
    }
    '/_layout/_header/pokemons/$id': {
      id: '/_layout/_header/pokemons/$id'
      path: '/pokemons/$id'
      fullPath: '/pokemons/$id'
      preLoaderRoute: typeof LayoutHeaderPokemonsIdLazyImport
      parentRoute: typeof LayoutHeaderImport
    }
    '/_layout/_header/pokemons/': {
      id: '/_layout/_header/pokemons/'
      path: '/pokemons'
      fullPath: '/pokemons'
      preLoaderRoute: typeof LayoutHeaderPokemonsIndexImport
      parentRoute: typeof LayoutHeaderImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  LayoutRoute: LayoutRoute.addChildren({
    LayoutHeaderRoute: LayoutHeaderRoute.addChildren({
      LayoutHeaderHeavyRoute,
      LayoutHeaderErrorLazyRoute,
      LayoutHeaderLightLazyRoute,
      LayoutHeaderIndexLazyRoute,
      LayoutHeaderPokemonsSearchRoute,
      LayoutHeaderPokemonsIdLazyRoute,
      LayoutHeaderPokemonsIndexRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_header"
      ]
    },
    "/_layout/_header": {
      "filePath": "_layout/_header.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_header/heavy",
        "/_layout/_header/error",
        "/_layout/_header/light",
        "/_layout/_header/",
        "/_layout/_header/pokemons/search",
        "/_layout/_header/pokemons/$id",
        "/_layout/_header/pokemons/"
      ]
    },
    "/_layout/_header/heavy": {
      "filePath": "_layout/_header/heavy.tsx",
      "parent": "/_layout/_header"
    },
    "/_layout/_header/error": {
      "filePath": "_layout/_header/error.lazy.tsx",
      "parent": "/_layout/_header"
    },
    "/_layout/_header/light": {
      "filePath": "_layout/_header/light.lazy.tsx",
      "parent": "/_layout/_header"
    },
    "/_layout/_header/": {
      "filePath": "_layout/_header/index.lazy.tsx",
      "parent": "/_layout/_header"
    },
    "/_layout/_header/pokemons/search": {
      "filePath": "_layout/_header/pokemons/search.tsx",
      "parent": "/_layout/_header"
    },
    "/_layout/_header/pokemons/$id": {
      "filePath": "_layout/_header/pokemons/$id.lazy.tsx",
      "parent": "/_layout/_header"
    },
    "/_layout/_header/pokemons/": {
      "filePath": "_layout/_header/pokemons/index.tsx",
      "parent": "/_layout/_header"
    }
  }
}
ROUTE_MANIFEST_END */
